### ISSUE TITLE
Can't change tab border height

### ISSUE THREAD

**Issue by shaulhadar** [JKnorr91/ion-slide-box-tabs#1]
Hi Jknor, first of all i would like to say amazing work!!

I was trying to make the tab border a bit bigger, like 4px or so to test a design, but i couldn't find in what class to edit it...

Please help me to edit this..

Thanks,
Shaul.

**Comment by JKnorr91** [comment]
Hi shaulhadar,

changing the height is really simple: Just search for the ".tab-indicator-wrapper" class in the scss or css and change the "height" and the "-webkit-transform: translateY" property to a value you like.

**Comment by shaulhadar** [comment]
Great man, it works!

Thanks so much :)
