### ISSUE TITLE
How to update tabs (insert/remove) dinamically with ng-repeat

### ISSUE THREAD

**Issue by vinimendes3** [JKnorr91/ion-slide-box-tabs#26]
Actually I am adding slides dinamically using ng-repeat, and whenever user "pull to refresh" the page, new tabs are added or removed from tabs. I'm controlling this from my controller, but when I change the variable which controls ng-repeat content, the new tabs added not appears, and removed tabs keep showing on previous tabs. How can I update this whenever I want?

Thanks in advance

**Comment by caocuongajax** [comment]
Do you have any solution for this?
Could you help me?

**Comment by Elvincth** [comment]
Do you have any solution for this? +1
